name: Release
on:
    push:
        tags:
            - v*
        branches:
            - main
env:
    FORCE_COLOR: true
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    REPO: roothheo/bashcord
    USERNAME: GitHub-Actions

permissions: write-all

jobs:
    Build:
        name: Build Bashcord
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile

            - name: Build web
              run: pnpm buildWebStandalone

            - name: Build
              run: pnpm buildStandalone

            - name: Generate plugin list
              run: pnpm generatePluginJson dist/plugins.json

            - name: Generate Equicord plugin list
              run: pnpm generateEquicordPluginJson dist/equicordplugins.json

            # Adapte les chemins ci-dessous selon la structure de Bashcord
            - name: Collect files to be released
              run: |
                  cd dist
                  mkdir release
                  cp browser/browser.* release || true
                  cp Vencord.user.{js,js.LEGAL.txt} release || true
                  cp *.{json,zip,asar} release || true
                  cp desktop/* release || true
                  for file in equibop/*; do
                    filename=$(basename "$file")
                    cp "$file" "release/equibop${filename^}" || true
                  done
                  find release -size 0 -delete || true
                  rm release/package.json || true
                  rm release/*.map || true

            - name: Upload Bashcord Release
              if: ${{ github.ref_name == 'main' }}
              run: |
                  gh release upload latest --clobber dist/release/*

            # Si tu veux pousser les plugins.json dans un autre repo, adapte REPO
            - name: Upload Plugins JSON to Bashcord repo
              run: |
                  git config --global user.name "GitHub-Actions"
                  git config --global user.email actions@github.com
                  git clone https://$USERNAME:$GITHUB_TOKEN@github.com/$REPO.git plugins
                  cd plugins
                  cp ../dist/release/*plugins.json .
                  git add -A
                  git commit -m "Plugins for https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA"
                  git push --force https://$USERNAME:$GITHUB_TOKEN@github.com/$REPO.git
