name: Test
on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

env:
    FORCE_COLOR: true

jobs:
    Test:
        name: Test Bashcord
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run tests
              run: pnpm test

            - name: Run linting
              run: pnpm lint

            - name: Type check
              run: pnpm type-check
